### PR TITLE
Fix typo in English, add some French strings

### PR DESCRIPTION
**Pull request by Gustry**
* I don't think that "models" and "styles" need a capital letter.
* For "WPS" not sure it has a meaning for end users on Lizmap. Lizmap is a frontend for the WPS "protocol", I think having "Processing" is better for end user, having no idea what is WPS.

image

### CODE REVIEW

**Comment by Gustry** [comment]
They are still some strings to add, it's not fully translated, in the JS code.

@dmarteau @rldhont Do you have an idea or is-there a dev planned to have QGIS native processing algorithm translated as well ?
image

**Review by rldhont — APPROVED** [review]

**Comment by Gustry** [comment]
@nworr What is the best way to add translations in static JS files, such as this line ? https://github.com/3liz/lizmap-wps-web-client-module/blob/master/wps/www/wps.js#L194 (and many others)

Similar as in PgMetadata 
https://github.com/3liz/lizmap-pgmetadata-module/blob/main/pgmetadata/www/pgmetadata.js#L71
To initiate a similar dictionary ?

**Comment by nworr** [comment]
Initiate a dictionnary like in pgMetadata is a smart way, yes.
The best way may be to generate html on js side using a template engine,  but it's not a simple task ...

**Comment by Gustry** [comment]
@nworr They are more strings to do in the wps.js file, I will do a separate PR for it.

CC @mdouchin after discussion

**Review by nworr — APPROVED** [review]

**Comment by Gustry** [comment]
It should be better @mdouchin even if @nworr approved before :)

**Pull request merged**
